version: '4'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papi
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: andprof/ac2_ca:latest
    networks:
      - default  # Certifique-se de que está usando a rede adequada
    environment:
      DB_HOST: database
    ports:
      - "8585:8080"
volumes:
  db-volume: